name: Feature Request
description: Suggest a new feature or improvement for NumiSync Wizard
title: "[Feature] "
labels: ["enhancement"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to suggest an improvement. Please fill out as much detail as you can to help us understand the request.

  - type: textarea
    id: problem
    attributes:
      label: What problem does this solve?
      description: Describe the workflow or limitation that led to this request. "I'm trying to do X but I can't because..."
      placeholder: "I'm trying to..."
    validations:
      required: true

  - type: textarea
    id: solution
    attributes:
      label: Describe the feature you'd like
      description: A clear description of what you want NumiSync Wizard to do.
      placeholder: "I'd like it if..."
    validations:
      required: true

  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives or workarounds you've considered
      description: Have you found any workaround? Are there other ways this could be solved?
      placeholder: "Currently I work around this by..."
    validations:
      required: false

  - type: textarea
    id: additional
    attributes:
      label: Additional Context
      description: Any screenshots, mockups, or examples from other tools that illustrate the idea.
      placeholder: "Screenshots, links, or other context..."
    validations:
      required: false
